name: db
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: 'none'

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  stormberry: ^0.14.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^4.0.0
  test: ^1.24.0
